### ISSUE TITLE
Hi i am using this for one of my project

### ISSUE THREAD

**Issue by ramanprtap** [gurayyarar/AdminBSBMaterialDesign#144] opened 2018-09-04 04:56 UTC
its a very good project i just want to know that is there any option to make the side menu collapsible its very much needed for me please let me know 

Thanks 
Raman Pratap

**Comment by acjh** [comment] 2018-09-04 04:58
Duplicate of #4

**Comment by ramanprtap** [comment] 2018-09-04 05:11
Thanks for instant reply will use it and let you know 

again thank you very much

**Closed** 2018-12-13 07:05 UTC
